allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - wrangler@4.136.3
  - "@cloudflare/vitest-plugin@1.2.3"
  - "@turbo/darwin-64@2.11.3"
  - "@turbo/darwin-arm64@2.11.3"
  - "@turbo/linux-64@2.11.3"
  - "@turbo/linux-arm64@2.11.3"
  - "@turbo/windows-64@2.11.3"
  - "@turbo/windows-arm64@2.11.3"
  - turbo@2.11.3
